---
AllCops:
  TargetRubyVersion: 2.3

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/EmptyMethod:
  EnforcedStyle: expanded
